spring.application.name=gym-management

# MySQL Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3308/gym_smartbell?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration (aligned with JwtService @Value)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
application.security.jwt.expiration=86400000
application.security.jwt.refresh-expiration=604800000

# SQL debug logging (remove in prod)
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Server
server.port=8080

# Jackson - dates as strings not timestamps
spring.jackson.serialization.write-dates-as-timestamps=false

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Logging
logging.level.com.gymapp=DEBUG
logging.level.org.springframework.security=WARN

# Actuator (healthcheck Docker)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# Groq API
groq.api.key=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
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.3-70b-versatile

