// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAonCh2Y0yVMHo1wrZ5FeBxb7WePwFfgpI',
    appId: '1:359901746452:web:8b20577dfbac87d559de01',
    messagingSenderId: '359901746452',
    projectId: 'smartbell-gym',
    authDomain: 'smartbell-gym.firebaseapp.com',
    storageBucket: 'smartbell-gym.firebasestorage.app',
    measurementId: 'G-3C2CLKCMJ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASy13I1pJRMouC6B3SOxX25bqrjuHSTzY',
    appId: '1:359901746452:android:f20ea9067a0ac44659de01',
    messagingSenderId: '359901746452',
    projectId: 'smartbell-gym',
    storageBucket: 'smartbell-gym.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBa1dFF7knwcdlSCf6Xx70RvQMiU6758Z8',
    appId: '1:359901746452:ios:e1b379989788bd9259de01',
    messagingSenderId: '359901746452',
    projectId: 'smartbell-gym',
    storageBucket: 'smartbell-gym.firebasestorage.app',
    iosBundleId: 'com.gymapp.smartbellMobile',
  );

}